2023-11-22 22:53:58,434 INFO    MainThread:1987708 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-22 22:53:58,435 INFO    MainThread:1987708 [wandb_setup.py:_flush():76] Configure stats pid to 1987708
2023-11-22 22:53:58,435 INFO    MainThread:1987708 [wandb_setup.py:_flush():76] Loading settings from /home/sanoojan/.config/wandb/settings
2023-11-22 22:53:58,435 INFO    MainThread:1987708 [wandb_setup.py:_flush():76] Loading settings from /home/sanoojan/Paint_for_swap/wandb/settings
2023-11-22 22:53:58,435 INFO    MainThread:1987708 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-22 22:53:58,435 INFO    MainThread:1987708 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-22 22:53:58,435 INFO    MainThread:1987708 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main_swap.py', 'program_abspath': '/home/sanoojan/Paint_for_swap/main_swap.py', 'program': 'main_swap.py'}
2023-11-22 22:53:58,435 INFO    MainThread:1987708 [wandb_init.py:_log_setup():524] Logging user logs to /home/sanoojan/Paint_for_swap/wandb/run-20231122_225358-9aqoh7xq/logs/debug.log
2023-11-22 22:53:58,436 INFO    MainThread:1987708 [wandb_init.py:_log_setup():525] Logging internal logs to /home/sanoojan/Paint_for_swap/wandb/run-20231122_225358-9aqoh7xq/logs/debug-internal.log
2023-11-22 22:53:58,436 INFO    MainThread:1987708 [wandb_init.py:init():564] calling init triggers
2023-11-22 22:53:58,437 INFO    MainThread:1987708 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'_metadata': ContainerMetadata(ref_type=typing.Any, object_type=None, optional=True, key=None, flags={}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {}), key_type=typing.Any, element_type=typing.Any), '_parent': None, '_flags_cache': {'readonly': None, 'struct': None, 'allow_objects': None, 'no_deepcopy_set_nodes': None}, '_content': {'model': {'base_learning_rate': 1e-05, 'target': 'ldm.models.diffusion.ddpm.LatentDiffusion', 'params': {'linear_start': 0.00085, 'linear_end': 0.012, 'num_timesteps_cond': 1, 'log_every_t': 200, 'timesteps': 1000, 'first_stage_key': 'inpaint', 'cond_stage_key': 'image', 'image_size': 64, 'channels': 4, 'cond_stage_trainable': True, 'conditioning_key': 'crossattn', 'monitor': 'val/loss_simple_ema', 'u_cond_percent': 0.2, 'scale_factor': 0.18215, 'use_ema': False, 'scheduler_config': {'target': 'ldm.lr_scheduler.LambdaLinearScheduler', 'params': {'warm_up_steps': [10000], 'cycle_lengths': [10000000000000], 'f_start': [1e-06], 'f_max': [1.0], 'f_min': [1.0]}}, 'unet_config': {'target': 'ldm.modules.diffusionmodules.openaimodel.UNetModel', 'params': {'image_size': 32, 'in_channels': 9, 'out_channels': 4, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'use_spatial_transformer': True, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'add_conv_in_front_of_unet': False}}, 'first_stage_config': {'target': 'ldm.models.autoencoder.AutoencoderKL', 'params': {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'cond_stage_config': {'target': 'ldm.modules.encoders.modules.FrozenCLIPImageEmbedder', 'other_params': {'clip_weight': 0.1, 'ID_weight': 0.9, 'Landmark_cond': True, 'Landmarks_weight': 0.05, 'arcface_path': '/home/sanoojan/e4s/pretrained_ckpts/auxiliray/model_ir_se50.pth', 'concat_feat': False, 'land_mark_id_seperate_layers': False, 'multi_scale_ID': False, 'sep_head_att': False, 'normalize': False, 'Additional_config': {'Reconstruct_initial': True, 'Reconstruct_DDIM_steps': 5, 'ID_loss_weight': 0.3, 'LPIPS_loss_weight': 0.0, 'Landmark_loss_weight': 0}}}}}, 'data': {'target': 'main_swap.DataModuleFromConfig', 'params': {'batch_size': 4, 'wrap': False, 'train': {'target': 'ldm.data.celebA.CelebAdataset', 'params': {'state': 'train', 'dataset_dir': '/home/sanoojan/Paint_for_swap/dataset/FaceData/CelebAMask-HQ/', 'arbitrary_mask_percent': 0.5, 'image_size': 512, 'data_seed': 0, 'gray_outer_mask': True, 'preserve_mask': [1, 2, 4, 5, 8, 9, 6, 7, 10, 11, 12, 17]}}, 'validation': {'target': 'ldm.data.celebA.CelebAdataset', 'params': {'state': 'validation', 'dataset_dir': '/home/sanoojan/Paint_for_swap/dataset/FaceData/CelebAMask-HQ/', 'arbitrary_mask_percent': 0.5, 'image_size': 512, 'data_seed': 0, 'gray_outer_mask': True, 'preserve_mask': [1, 2, 4, 5, 8, 9, 6, 7, 10, 11, 12, 17]}}, 'test': {'target': 'ldm.data.celebA.CelebAdataset', 'params': {'state': 'test', 'dataset_dir': '/home/sanoojan/Paint_for_swap/dataset/FaceData/CelebAMask-HQ/', 'arbitrary_mask_percent': 0.5, 'image_size': 512, 'gray_outer_mask': True, 'preserve_mask': [1, 2, 4, 5, 8, 9, 6, 7, 10, 11, 12, 17]}}}}}}
2023-11-22 22:53:58,437 INFO    MainThread:1987708 [wandb_init.py:init():614] starting backend
2023-11-22 22:53:58,437 INFO    MainThread:1987708 [wandb_init.py:init():618] setting up manager
2023-11-22 22:53:58,439 INFO    MainThread:1987708 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-11-22 22:53:58,441 INFO    MainThread:1987708 [wandb_init.py:init():624] backend started and connected
2023-11-22 22:53:58,658 ERROR   MainThread:1987708 [wandb_init.py:init():1194] error
Traceback (most recent call last):
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    run = wi.init()
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 629, in init
    run = Run(
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 566, in __init__
    self._init(
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 698, in _init
    self._config._update(config, ignore_locked=True)
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 255, in _sanitize
    val = json_friendly_val(val)
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/site-packages/wandb/util.py", line 671, in json_friendly_val
    converted = asdict(val)
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/dataclasses.py", line 1073, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/dataclasses.py", line 1080, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/share/softwares/anaconda/anaconda3/envs/paint2/lib/python3.8/dataclasses.py", line 1110, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
2023-11-22 22:53:59,812 WARNING MsgRouterThr:1987708 [router.py:message_loop():77] message_loop has been closed
